QueueSimulator:
  Q1:
    servers: 2
    capacity: 3
    arrival_interval: [1, 4]
    departure_interval: [3, 4]
    first_arrival: 1.5
    rand:
      A: 512345
      C: 373621
      M: 2**31
      seed: 100
  Q2:
    servers: 1
    capacity: 5
    arrival_interval: [1, 0]
    departure_interval: [2, 3]
    first_arrival: 100000
    rand:
      A: 512345
      C: 373621
      M: 2**31
      seed: 100
